knpu_oauth2_client:
    clients:
        google:
            client_id: '%env(OAUTH_GOOGLE_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_SECRET)%'
            type: google
            redirect_route: connect_google_check
            redirect_params: {}