vich_uploader:
    db_driver: orm
    mappings:
        profile_picture:
            upload_destination: profile_picture_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
